name: project_mad
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dots_indicator: ^2.1.0
  firebase_core: ^2.3.0
  provider: ^6.0.4
  get: 4.6.5
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  get_storage: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.2.15

flutter_native_splash:
  color: "#1a1a1a"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: fill

  android_12:
    color: "#1a1a1a"
    image: assets/splash.png
    android: true
    ios: true
    android_gravity: fill

flutter:
  assets:
    - assets/gambar/logo_2.png
    - assets/gambar/logo_1.png
    - assets/gambar/Screenshot_4.png
    - assets/gambar/Screenshot_3.png
    - assets/gambar/Screenshot_2.png
    - assets/gambar/Screenshot_1.png
    - assets/gambar/minuman.png
  uses-material-design: true
