// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnVNeDA9GmpJwZnuIvpkhjxbbN6CMfl60',
    appId: '1:944049190638:web:911596eda5b4467f9a25ff',
    messagingSenderId: '944049190638',
    projectId: 'project-mad-c4c53',
    authDomain: 'project-mad-c4c53.firebaseapp.com',
    storageBucket: 'project-mad-c4c53.appspot.com',
    measurementId: 'G-K3Z1937YTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1jHL-nXcDyrnZztgrsrezit4aYsSdRl8',
    appId: '1:944049190638:android:786b7b46785372f89a25ff',
    messagingSenderId: '944049190638',
    projectId: 'project-mad-c4c53',
    storageBucket: 'project-mad-c4c53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_fOS2E45joR3rI3IG6O9VwNQnG16PSIo',
    appId: '1:944049190638:ios:411a081481f3f9719a25ff',
    messagingSenderId: '944049190638',
    projectId: 'project-mad-c4c53',
    storageBucket: 'project-mad-c4c53.appspot.com',
    androidClientId: '944049190638-44g26lhd69sfkpntiloc1crk0rn3oafu.apps.googleusercontent.com',
    iosClientId: '944049190638-k1pnb24h4sqhfgnsflm96r984dvfvugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_fOS2E45joR3rI3IG6O9VwNQnG16PSIo',
    appId: '1:944049190638:ios:411a081481f3f9719a25ff',
    messagingSenderId: '944049190638',
    projectId: 'project-mad-c4c53',
    storageBucket: 'project-mad-c4c53.appspot.com',
    androidClientId: '944049190638-44g26lhd69sfkpntiloc1crk0rn3oafu.apps.googleusercontent.com',
    iosClientId: '944049190638-k1pnb24h4sqhfgnsflm96r984dvfvugc.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMad',
  );
}
